# Generated by Django 3.2.3 on 2021-06-03 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.TextField(max_length=150)),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_user', to=settings.AUTH_USER_MODEL)),
                ('replies', models.ManyToManyField(related_name='reply', to='posts.Comments')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_url', models.URLField(null=True)),
                ('bg_color', models.CharField(max_length=6)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('is_video_post', models.BooleanField(default=False)),
                ('comments', models.ManyToManyField(related_name='comment', to='posts.Comments')),
                ('likes', models.ManyToManyField(related_name='user_likes', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
